### ISSUE TITLE
Is possible to remove bg from tab?

### ISSUE THREAD

**Issue by gotoco** [endel/vim-github-colorscheme#11]
Hi usually I don't use tab's in my code, but in Linux kernel, you don't have a choose. Tabs are part of codings standard.
How can I remove the background from them? I wanted to use this color scheme because is really nice, but colored tabs are really annoying:

<img width="1268" alt="screen shot 2016-07-04 at 07 56 18" src="https://cloud.githubusercontent.com/assets/1118727/16553077/ee1ad580-41bd-11e6-9c2c-62f0bba061ed.png">

**Comment by sw561** [comment]
You can remove the `SpecialKey` highlighting command (line 34).

**Comment by gotoco** [comment]
Thanks for reply It helped me a lot
